### ISSUE TITLE
Matters of opinion in the readme

### ISSUE THREAD

**Issue by the-maldridge** [netzverweigerer/vpm#1]
In general, READMEs do not contain opinion that is so derisive of an upstream project.  Your statement that "XBPS is hard to use and has a heavy learning curve thanks to its diversed toolchain and hard to remember commandline arguments" implies that it is universally hard to use when this is not the case.  You have personally encountered trouble but there are many who came before you that disagree with the difficulty of XBPS.

I have no intention of discussing your choice of language, I do however believe you should reconsider the very pointed criticisms of an upstream project.

**Comment by netzverweigerer** [comment]
Hi,

thank you for reporting this, I changed the README.md file a lot, after re-considering some aspects of it. I don't want to be vpm to be meant as criticising XBPS by all means, and would always love to see this as a friendly project, especially for XBPS itself. 

Again, thanks for reporting this, I changed the README file, I hope this will not sound offending to anyone anymore, if so, please let me know!

All the best,

Armin
