### ISSUE TITLE
Mistake in script

### ISSUE THREAD

**Issue by emakei** [netzverweigerer/vpm#2]
Parameters should be same?
```
513: msg "autoremove: Removing orphaned packages (xbps-remove -v -Q)"
514: xbps-remove -v -O
```

**Comment by netzverweigerer** [comment]
Thanks for reporting this and sorry for the delay. Fixed.

**Comment by lanxsatura** [comment]
I noticed 2 mistakes:

The first one:
`225:    echo "cleanup (cl)                 - Clean up cache directory"`
`226:    t "xbps-remove -v -O"`
`227:    echo "autoremove (ar)              - Remove orphaned packages"`
`228:    t "xbps-remove -v -O"`
Line 226 and 228 display the same command.
Instead, the command to remove orphans (line 228) should be 'xbps-remove -v **-o**' (with a **lowercase o**).

The second one:
`547:  cleanup|clean|cl)`
`548:      msg "Cleaning up packages (will remove orphaned packages) (xbps-remove -v -O $@)"`
Line 548, the _cleanup_ argument doesn't remove orphans but cleans the cache directory, so, instead, it should be something like:
    msg "Cleaning up **cache directory** (will remove **obsolete binary packages**) (xbps-remove -v -O $@)"
