### ISSUE TITLE
package for void

### ISSUE THREAD

**Issue by jcgruenhage** [netzverweigerer/vpm#4]

**Comment by Goorzhel** [comment]
```
pkgname=vpm
version=1.2a
revision=1
archs=noarch
short_desc="An XBPS package management helper for VoidLinux"
maintainer="... <...>"
license="GPL-3.0-or-later"
homepage="https://github.com/netzverweigerer/vpm"
distfiles="https://github.com/netzverweigerer/${pkgname}/archive/{version}.tar.gz"
checksum=e2c940dd96bc6d67251c30549c1a1aa0826cfc9b6be582109c01a6af69cd3ed5

do_install() {
        vbin vpm
}
```
If @netzverweigerer is interested in maintaining the XBPS package as well as the script, sending this in a PR to void-linux/void-packages ought to do it.

**Comment by netzverweigerer** [comment]
Wow. First of all, thanks so much for bringing this up. I had to think a couple of weeks about this and also discussed with some friends and asked them how they would proceed here.

So there's this little background story: When I wrote VPM years ago, I proposed this to the Void community, and the guy who back then was developing XBPS basically told me that "this won't ever get merged". Thinking about what to do with this project, I ended up choosing GPL3 as a license for it and never bothered with developing a proper bash-completion or zsh-completion for it.

I'm thankful to get some feedback like this however, and of course I'd be totally fine with maintaining these two. 

Again, thank you. Much welcome.

**Comment by jjzmajic** [comment]
Sorry for the delay @netzverweigerer. So, are we gonna be doing this (the void package)? PS: I could possibly do the zsh completions. It's just a question of calling the current `_xbps` functions properly.

**Comment by Kelvino9** [comment]
Having VPM as a package would be really nice. Using it on both my computers.

**Comment by netzverweigerer** [comment]
Yeah absolutely, let's do this!

**Comment by netzverweigerer** [comment]
Created a pull request.

https://github.com/void-linux/void-packages/pull/19231

**Comment by keshto** [comment]
Can this be closed now? (a new release would be nice also)

**Comment by jcgruenhage** [comment]
@keshto yes, can be closed now.
